config/routes.rb
Rails.application.routes.draw do

  delete '/products/:id', to: 'products#destroy'
  patch '/products/:id', to: 'products#update'
  post '/products', to: 'products#create'
  get '/products/new', to: 'products#new', as: :new_product
  get 'products/index'
  get '/products', to: 'products#index' 
  get '/products/:id', to: 'products#show', as: :product 
  get '/products/:id/edit', to: 'products#edit', as: :edit_product
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
      if @product.save 
        redirect_to products_path, notice: 'Tu producto se ha creado correctamente'
      else
        render :new , status: :unprocessable_entity
      end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
        redirect_to products_path, notice: 'Tu producto se ha actualizado'

    else
      render :edit, status: :unprocessable_entity
  end
end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: 'Tu producto se ha eliminado', status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Siscobank</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'shared/flash' %>
   <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>

    <% @product.errors.full_messages.each do |error| %>
     <div>
        <%= error%>
     </div>    
    <%end%>
    <div>
        <%= form.label :title%>
        <%= form.text_field :title%>
    </div>

    <div>
        <%= form.label :description%>
        <%= form.text_area :description%>
    </div>

    <div>
        <%= form.label :price%>
        <%= form.number_field :price%>
    </div>

    <%= form.submit %>

<%end%>

app/views/products/edit.html.erb
<h2> Editar producto </h2>

<%= render 'form'%>

app/views/products/index.html.erb
<h1>Productos</h1>

<% @products.each do |product| %> <!-- Recorre todos los productos -->
    <%= link_to product_path(product), class: 'product' do  %>
        <h2><%= product.title %> </h2>
        <span> <%= product.price %>$</span>
    <% end %>
<% end %>

app/views/products/new.html.erb
<h1> Agregar producto </h1>

<%= render 'form'%>

app/views/products/show.html.erb
<h1 class= 'title'><%= @product.title %></h1>
<p class= 'description'> <%= @product.description%></p>
<span class = 'price'> <%= @product.price%>$ </span>
<%= link_to 'Editar Producto'  , edit_product_path(@product)%>
<%= link_to 'Eliminar Producto'  , product_path(@product), data:{
    turbo_method: :delete,
    turbo_method: 'Estas seguro?'
}%>

app/views/shared/_flash.html.erb
<%= notice%>

<%= alert%>

app/views/shared/_header.html.erb
<%=link_to products_path do%>
<h1>Vendelo</h1>
<% end %>
<%= link_to 'Agregar producto' , new_product_path%>